version: "3.8"
services:
  api:
    build: .
    command: cargo run
    env_file:
      - ./coffeenote-api/env_files/db.env
    ports:
      - "55301:55301"
    depends_on:
      - db
    volumes:
      - ./Cargo.lock:/app/Cargo.lock
      - ./Cargo.toml:/app/Cargo.toml
      - ./src:/app/src
      - ./coffeenote-api:/app/coffeenote-api
      - ./coffeenote-core:/app/coffeenote-core
  db:
    image: postgres:alpine
    env_file:
      - coffeenote-api/env_files/db.env
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
volumes:
  dbdata: