[package]
name = "coffeenote-core"
version = "0.1.0"
edition = "2018"

[dependencies]
uuid = { version = "0.8", features = ["v4"] }
chrono = "0.4"
async-trait = "0.1"
futures = "0.3"

[dev-dependencies]
quickcheck = "1"
tokio = { version = "1", features = ["full"] }