name: run-test
on: [push]
env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Run test
        uses: mtwtkman/rust-action@master
        with:
          cmd: "rustup component add rustfmt && cargo test"