name: run-test
on: [push]
env:
  CARGO_TERM_COLOR: always
  DOCKER_BUILDKIT: 1
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Build
        run: docker build -t app .
      - name: Run tests
        run: docker run app cargo test